version: '2'
services:
  edr-lb:
    image: 'nginx:1.10-alpine'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  edr-api:
    environment:
      NODE_ENV: production
      PORT: 80
      PG: edr-db
    depends_on:
    - edr-db
    - redis

  edr-docs:
    image: 'vanuan/swagger-ui'
    ports:
      - 82:80

  edr-db:
    image: kiasaki/alpine-postgres:9.5
    environment:
      PGDATA: /var/lib/postgresql/data
    volumes:
      - edr-db:/var/lib/postgresql/data

  redis:
    image: 'redis'
    command: redis-server --appendonly yes
    expose:
      - '6379'
    volumes:
      - /data

  edr-uploader:
    build: ../edr-uploader
    volumes:
    - ./data:/data/edr/
    depends_on:
    - edr-db
    - edr-migrations
    environment:
      PG_CONNECTION_STRING: postgres://postgres@edr-db/postgres

  edr-migrations:
    build: ../edr-migrations
    command: sh -c '/wait-for-it.sh -t 100 edr-db:5432 && npm install && knex migrate:latest'
    depends_on:
      - edr-db
    environment:
      PG_CONNECTION_STRING: postgres://postgres@edr-db/postgres

  edr-static:
    image: 'vanuan/edrpou-static'
    environment:
      GRAPHQL_URL: "http://edr-graphql/"
    ports:
      - 83:80

  edr-graphql:
    image: 'vanuan/edrpou-graphql'
    ports:
      - 84:80

  elasticsearch:
    image: 'portefaix/elasticsearch:2.2.0'
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

  kibana:
    image: k0st/alpine-kibana
    ports:
     - 5601:5601
    depends_on:
     - elasticsearch

  edr-uploader-elastic:
    image: 'vanuan/edrpou-uploader:latest'
    depends_on:
     - edr-db
     - elasticsearch
    environment:
      PG_CONNECTION_STRING: postgres://postgres@edr-db/postgres
      ELASTIC_HOST: elasticsearch:9200
    command: sh -c '/wait-for-it.sh -t 100 elasticsearch:9200 && node /src/pgToElastic.js'


volumes:
  edr-db:
  elasticsearch:
